sudo: false
language: php
dist: trusty

env:
  global:
    - APPLICATION_ENV=test

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - EXECUTE_CS_CHECK=true
    - php: 7
    - php: hhvm

before_install:
  - mkdir -p build/logs
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then vendor/bin/phpunit --coverage-clover=./build/logs/clover.xml; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/bro-code fix src   ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/bro-code fix tests ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
